library(stringr)
library(xlsx)
library(tidyverse)
library(gridExtra)
library(data.table)
library(ggbiplot)
library(ggplot2)
library(dplyr)
library(gplots)
library(ggiraphExtra)
library(ggpubr)
library(corrplot)
library(Hmisc)
dataset <- read.xlsx("data_oil_bio.xlsx", sheetIndex = 1, encoding="UTF-8-BOM", fill = TRUE)

correlation <- cor(dataset[,35:50])
corrplot(correlation)
